project_id = "wdxelomsouudmidakxiz"

[functions.google-oauth-callback]
verify_jwt = false

[functions.get-podcast-episodes]
verify_jwt = false

[functions.pull-unfinished-tasks]
verify_jwt = false

[functions.log-error]
verify_jwt = false

[functions.create-tasks-from-priorities]
verify_jwt = false

[functions.ghl-webhook-add-member]
verify_jwt = false

[functions.ghl-webhook-remove-member]
verify_jwt = false

[functions.verify-member-email]
verify_jwt = false

[functions.add-mastermind-entitlement]
verify_jwt = false

[functions.import-tasks]
verify_jwt = false
