project_id = "wdxelomsouudmidakxiz"

[functions.google-oauth-callback]
verify_jwt = false

[functions.get-podcast-episodes]
verify_jwt = false

[functions.pull-unfinished-tasks]
verify_jwt = false

[functions.log-error]
verify_jwt = false
